// Code generated by protoc-gen-go.
// source: o2g_message.proto
// DO NOT EDIT!

/*
Package equtils is a generated protocol buffer package.

It is generated from these files:
	o2g_message.proto

It has these top-level messages:
	G2OMsgReq_Initiation
	G2OMsgReq
	G2OMsgRsp
	O2GMsgReq_ExecShellCmd
	O2GMsgRsp_ExecShellCmd
	O2GMsgReq
	O2GMsgRsp
*/
package equtils

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type G2OMsgReq_Op int32

const (
	G2OMsgReq_INITIATION G2OMsgReq_Op = 1
)

var G2OMsgReq_Op_name = map[int32]string{
	1: "INITIATION",
}
var G2OMsgReq_Op_value = map[string]int32{
	"INITIATION": 1,
}

func (x G2OMsgReq_Op) Enum() *G2OMsgReq_Op {
	p := new(G2OMsgReq_Op)
	*p = x
	return p
}
func (x G2OMsgReq_Op) String() string {
	return proto.EnumName(G2OMsgReq_Op_name, int32(x))
}
func (x *G2OMsgReq_Op) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(G2OMsgReq_Op_value, data, "G2OMsgReq_Op")
	if err != nil {
		return err
	}
	*x = G2OMsgReq_Op(value)
	return nil
}

type G2OMsgRsp_Result int32

const (
	G2OMsgRsp_SUCCEED G2OMsgRsp_Result = 1
	G2OMsgRsp_ERROR   G2OMsgRsp_Result = 2
)

var G2OMsgRsp_Result_name = map[int32]string{
	1: "SUCCEED",
	2: "ERROR",
}
var G2OMsgRsp_Result_value = map[string]int32{
	"SUCCEED": 1,
	"ERROR":   2,
}

func (x G2OMsgRsp_Result) Enum() *G2OMsgRsp_Result {
	p := new(G2OMsgRsp_Result)
	*p = x
	return p
}
func (x G2OMsgRsp_Result) String() string {
	return proto.EnumName(G2OMsgRsp_Result_name, int32(x))
}
func (x *G2OMsgRsp_Result) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(G2OMsgRsp_Result_value, data, "G2OMsgRsp_Result")
	if err != nil {
		return err
	}
	*x = G2OMsgRsp_Result(value)
	return nil
}

type O2GMsgReq_Op int32

const (
	O2GMsgReq_EXECSHELLCMD O2GMsgReq_Op = 1
)

var O2GMsgReq_Op_name = map[int32]string{
	1: "EXECSHELLCMD",
}
var O2GMsgReq_Op_value = map[string]int32{
	"EXECSHELLCMD": 1,
}

func (x O2GMsgReq_Op) Enum() *O2GMsgReq_Op {
	p := new(O2GMsgReq_Op)
	*p = x
	return p
}
func (x O2GMsgReq_Op) String() string {
	return proto.EnumName(O2GMsgReq_Op_name, int32(x))
}
func (x *O2GMsgReq_Op) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(O2GMsgReq_Op_value, data, "O2GMsgReq_Op")
	if err != nil {
		return err
	}
	*x = O2GMsgReq_Op(value)
	return nil
}

type O2GMsgRsp_Result int32

const (
	O2GMsgRsp_SUCCEED O2GMsgRsp_Result = 1
	O2GMsgRsp_ERROR   O2GMsgRsp_Result = 2
)

var O2GMsgRsp_Result_name = map[int32]string{
	1: "SUCCEED",
	2: "ERROR",
}
var O2GMsgRsp_Result_value = map[string]int32{
	"SUCCEED": 1,
	"ERROR":   2,
}

func (x O2GMsgRsp_Result) Enum() *O2GMsgRsp_Result {
	p := new(O2GMsgRsp_Result)
	*p = x
	return p
}
func (x O2GMsgRsp_Result) String() string {
	return proto.EnumName(O2GMsgRsp_Result_name, int32(x))
}
func (x *O2GMsgRsp_Result) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(O2GMsgRsp_Result_value, data, "O2GMsgRsp_Result")
	if err != nil {
		return err
	}
	*x = O2GMsgRsp_Result(value)
	return nil
}

type G2OMsgReq_Initiation struct {
	Id               *string `protobuf:"bytes,1,req" json:"Id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *G2OMsgReq_Initiation) Reset()         { *m = G2OMsgReq_Initiation{} }
func (m *G2OMsgReq_Initiation) String() string { return proto.CompactTextString(m) }
func (*G2OMsgReq_Initiation) ProtoMessage()    {}

func (m *G2OMsgReq_Initiation) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type G2OMsgReq struct {
	Op               *G2OMsgReq_Op         `protobuf:"varint,1,req,name=op,enum=equtils.G2OMsgReq_Op" json:"op,omitempty"`
	Initiation       *G2OMsgReq_Initiation `protobuf:"bytes,2,opt" json:"Initiation,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *G2OMsgReq) Reset()         { *m = G2OMsgReq{} }
func (m *G2OMsgReq) String() string { return proto.CompactTextString(m) }
func (*G2OMsgReq) ProtoMessage()    {}

func (m *G2OMsgReq) GetOp() G2OMsgReq_Op {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return G2OMsgReq_INITIATION
}

func (m *G2OMsgReq) GetInitiation() *G2OMsgReq_Initiation {
	if m != nil {
		return m.Initiation
	}
	return nil
}

type G2OMsgRsp struct {
	Res              *G2OMsgRsp_Result `protobuf:"varint,1,req,name=res,enum=equtils.G2OMsgRsp_Result" json:"res,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *G2OMsgRsp) Reset()         { *m = G2OMsgRsp{} }
func (m *G2OMsgRsp) String() string { return proto.CompactTextString(m) }
func (*G2OMsgRsp) ProtoMessage()    {}

func (m *G2OMsgRsp) GetRes() G2OMsgRsp_Result {
	if m != nil && m.Res != nil {
		return *m.Res
	}
	return G2OMsgRsp_SUCCEED
}

// O2G: Orchestrator to Guestagent
type O2GMsgReq_ExecShellCmd struct {
	ShellCmd         *string `protobuf:"bytes,1,req" json:"ShellCmd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *O2GMsgReq_ExecShellCmd) Reset()         { *m = O2GMsgReq_ExecShellCmd{} }
func (m *O2GMsgReq_ExecShellCmd) String() string { return proto.CompactTextString(m) }
func (*O2GMsgReq_ExecShellCmd) ProtoMessage()    {}

func (m *O2GMsgReq_ExecShellCmd) GetShellCmd() string {
	if m != nil && m.ShellCmd != nil {
		return *m.ShellCmd
	}
	return ""
}

type O2GMsgRsp_ExecShellCmd struct {
	Result           *string `protobuf:"bytes,1,req" json:"Result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *O2GMsgRsp_ExecShellCmd) Reset()         { *m = O2GMsgRsp_ExecShellCmd{} }
func (m *O2GMsgRsp_ExecShellCmd) String() string { return proto.CompactTextString(m) }
func (*O2GMsgRsp_ExecShellCmd) ProtoMessage()    {}

func (m *O2GMsgRsp_ExecShellCmd) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

type O2GMsgReq struct {
	Op               *O2GMsgReq_Op           `protobuf:"varint,1,req,name=op,enum=equtils.O2GMsgReq_Op" json:"op,omitempty"`
	ExecShellCmd     *O2GMsgReq_ExecShellCmd `protobuf:"bytes,2,opt" json:"ExecShellCmd,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *O2GMsgReq) Reset()         { *m = O2GMsgReq{} }
func (m *O2GMsgReq) String() string { return proto.CompactTextString(m) }
func (*O2GMsgReq) ProtoMessage()    {}

func (m *O2GMsgReq) GetOp() O2GMsgReq_Op {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return O2GMsgReq_EXECSHELLCMD
}

func (m *O2GMsgReq) GetExecShellCmd() *O2GMsgReq_ExecShellCmd {
	if m != nil {
		return m.ExecShellCmd
	}
	return nil
}

type O2GMsgRsp struct {
	Res              *O2GMsgRsp_Result       `protobuf:"varint,1,req,name=res,enum=equtils.O2GMsgRsp_Result" json:"res,omitempty"`
	ExecShellCmd     *O2GMsgRsp_ExecShellCmd `protobuf:"bytes,2,opt" json:"ExecShellCmd,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *O2GMsgRsp) Reset()         { *m = O2GMsgRsp{} }
func (m *O2GMsgRsp) String() string { return proto.CompactTextString(m) }
func (*O2GMsgRsp) ProtoMessage()    {}

func (m *O2GMsgRsp) GetRes() O2GMsgRsp_Result {
	if m != nil && m.Res != nil {
		return *m.Res
	}
	return O2GMsgRsp_SUCCEED
}

func (m *O2GMsgRsp) GetExecShellCmd() *O2GMsgRsp_ExecShellCmd {
	if m != nil {
		return m.ExecShellCmd
	}
	return nil
}

func init() {
	proto.RegisterEnum("equtils.G2OMsgReq_Op", G2OMsgReq_Op_name, G2OMsgReq_Op_value)
	proto.RegisterEnum("equtils.G2OMsgRsp_Result", G2OMsgRsp_Result_name, G2OMsgRsp_Result_value)
	proto.RegisterEnum("equtils.O2GMsgReq_Op", O2GMsgReq_Op_name, O2GMsgReq_Op_value)
	proto.RegisterEnum("equtils.O2GMsgRsp_Result", O2GMsgRsp_Result_name, O2GMsgRsp_Result_value)
}
