#!/bin/bash
set -x
set -e # exit on an error

BUILDROOT=`pwd`/../..

export GOPATH=$BUILDROOT/gopath
export GOBIN=$GOPATH/bin
export PATH=/usr/local/go/bin:$GOBIN:$PATH

# TODO: use some package manager
go get golang.org/x/sys/unix
go get github.com/spf13/viper
go get github.com/Sirupsen/logrus

echo "Compiling libearthquake-ld-preload.so"
# NOTE: go 1.5 or higher is required to use buildmode=c-shared
go build -buildmode=c-shared -o ../../bin/libearthquake-ld-preload.so
