language: go

sudo: required

go:
  - "1.10"

services:
  - docker

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzmq3-dev libnetfilter-queue-dev
  - go get golang.org/x/tools/cmd/cover github.com/axw/gocov/gocov github.com/mattn/goveralls github.com/modocache/gover

script:
  # Test the `nmz` Go package and get the coverage data
  # https://gist.github.com/rjeczalik/6f01430e8554bf59b88e
  - go list -f '{{if len .TestGoFiles}}"go test -race -cover -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./nmz/... | xargs -L 1 sh -c
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
  # Test some trivial things
  - go vet ./nmz/...
  - go fmt ./nmz/...
  # Test the entire Dockerfile
  - docker build -t osrg/namazu .

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3764d3d36d4961c05d54
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
