#! /bin/bash
set -e # exit on an error
set -x

pushd libearthquake
./build
popd

pushd inspector/preload
./build
popd

pushd inspector/java/base
mvn package
popd
cp -f inspector/java/base/target/earthquake-inspector.jar ./bin/
