#!/bin/bash

BUILDROOT=`pwd`/..

export GOPATH=$BUILDROOT/gopath
export GOBIN=$GOPATH/bin

REPO_PATH=`pwd`

go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
go get github.com/sevlyar/go-daemon
go get github.com/mitchellh/cli

EQUTILS_PATH=`pwd`/equtils
protoc --go_out=$EQUTILS_PATH -I$EQUTILS_PATH $EQUTILS_PATH/*.proto
protoc --go_out=$EQUTILS_PATH -I$BUILDROOT/inspector $BUILDROOT/inspector/*.proto

echo "Compiling libearthquake.so"
# NOTE: go 1.5 or higher is required to use buildmode=c-shared
go build -buildmode=c-shared -o ../bin/libearthquake.so libearthquake.go

echo "Compiling earthquake"
go build -o ../bin/earthquake $(ls *.go | grep -v libearthquake.go)
