// Code generated by protoc-gen-go.
// source: inspector_message.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	inspector_message.proto

It has these top-level messages:
	InspectorMsgReq_Event_FuncCall
	InspectorMsgReq_Event_FuncReturn
	InspectorMsgReq_Event_Exit
	InspectorMsgReq_Event
	InspectorMsgReq_Initiation
	InspectorMsgReq_JavaSpecificFields_StackTraceElement
	InspectorMsgReq_JavaSpecificFields_Params
	InspectorMsgReq_JavaSpecificFields
	InspectorMsgReq
	InspectorMsgRsp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type InspectorMsgReq_Event_Type int32

const (
	InspectorMsgReq_Event_FUNC_CALL   InspectorMsgReq_Event_Type = 1
	InspectorMsgReq_Event_FUNC_RETURN InspectorMsgReq_Event_Type = 2
	InspectorMsgReq_Event_EXIT        InspectorMsgReq_Event_Type = 3
)

var InspectorMsgReq_Event_Type_name = map[int32]string{
	1: "FUNC_CALL",
	2: "FUNC_RETURN",
	3: "EXIT",
}
var InspectorMsgReq_Event_Type_value = map[string]int32{
	"FUNC_CALL":   1,
	"FUNC_RETURN": 2,
	"EXIT":        3,
}

func (x InspectorMsgReq_Event_Type) Enum() *InspectorMsgReq_Event_Type {
	p := new(InspectorMsgReq_Event_Type)
	*p = x
	return p
}
func (x InspectorMsgReq_Event_Type) String() string {
	return proto.EnumName(InspectorMsgReq_Event_Type_name, int32(x))
}
func (x *InspectorMsgReq_Event_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(InspectorMsgReq_Event_Type_value, data, "InspectorMsgReq_Event_Type")
	if err != nil {
		return err
	}
	*x = InspectorMsgReq_Event_Type(value)
	return nil
}
func (InspectorMsgReq_Event_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

type InspectorMsgReq_Type int32

const (
	InspectorMsgReq_EVENT      InspectorMsgReq_Type = 1
	InspectorMsgReq_INITIATION InspectorMsgReq_Type = 2
)

var InspectorMsgReq_Type_name = map[int32]string{
	1: "EVENT",
	2: "INITIATION",
}
var InspectorMsgReq_Type_value = map[string]int32{
	"EVENT":      1,
	"INITIATION": 2,
}

func (x InspectorMsgReq_Type) Enum() *InspectorMsgReq_Type {
	p := new(InspectorMsgReq_Type)
	*p = x
	return p
}
func (x InspectorMsgReq_Type) String() string {
	return proto.EnumName(InspectorMsgReq_Type_name, int32(x))
}
func (x *InspectorMsgReq_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(InspectorMsgReq_Type_value, data, "InspectorMsgReq_Type")
	if err != nil {
		return err
	}
	*x = InspectorMsgReq_Type(value)
	return nil
}
func (InspectorMsgReq_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

type InspectorMsgRsp_Result int32

const (
	InspectorMsgRsp_ACK   InspectorMsgRsp_Result = 1
	InspectorMsgRsp_ERROR InspectorMsgRsp_Result = 2
	InspectorMsgRsp_END   InspectorMsgRsp_Result = 3
)

var InspectorMsgRsp_Result_name = map[int32]string{
	1: "ACK",
	2: "ERROR",
	3: "END",
}
var InspectorMsgRsp_Result_value = map[string]int32{
	"ACK":   1,
	"ERROR": 2,
	"END":   3,
}

func (x InspectorMsgRsp_Result) Enum() *InspectorMsgRsp_Result {
	p := new(InspectorMsgRsp_Result)
	*p = x
	return p
}
func (x InspectorMsgRsp_Result) String() string {
	return proto.EnumName(InspectorMsgRsp_Result_name, int32(x))
}
func (x *InspectorMsgRsp_Result) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(InspectorMsgRsp_Result_value, data, "InspectorMsgRsp_Result")
	if err != nil {
		return err
	}
	*x = InspectorMsgRsp_Result(value)
	return nil
}
func (InspectorMsgRsp_Result) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

type InspectorMsgReq_Event_FuncCall struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InspectorMsgReq_Event_FuncCall) Reset()                    { *m = InspectorMsgReq_Event_FuncCall{} }
func (m *InspectorMsgReq_Event_FuncCall) String() string            { return proto.CompactTextString(m) }
func (*InspectorMsgReq_Event_FuncCall) ProtoMessage()               {}
func (*InspectorMsgReq_Event_FuncCall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InspectorMsgReq_Event_FuncCall) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type InspectorMsgReq_Event_FuncReturn struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InspectorMsgReq_Event_FuncReturn) Reset()         { *m = InspectorMsgReq_Event_FuncReturn{} }
func (m *InspectorMsgReq_Event_FuncReturn) String() string { return proto.CompactTextString(m) }
func (*InspectorMsgReq_Event_FuncReturn) ProtoMessage()    {}
func (*InspectorMsgReq_Event_FuncReturn) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1}
}

func (m *InspectorMsgReq_Event_FuncReturn) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type InspectorMsgReq_Event_Exit struct {
	ExitCode         *int32 `protobuf:"varint,1,req,name=exitCode" json:"exitCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *InspectorMsgReq_Event_Exit) Reset()                    { *m = InspectorMsgReq_Event_Exit{} }
func (m *InspectorMsgReq_Event_Exit) String() string            { return proto.CompactTextString(m) }
func (*InspectorMsgReq_Event_Exit) ProtoMessage()               {}
func (*InspectorMsgReq_Event_Exit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InspectorMsgReq_Event_Exit) GetExitCode() int32 {
	if m != nil && m.ExitCode != nil {
		return *m.ExitCode
	}
	return 0
}

type InspectorMsgReq_Event struct {
	Type             *InspectorMsgReq_Event_Type       `protobuf:"varint,1,req,name=type,enum=pb.InspectorMsgReq_Event_Type" json:"type,omitempty"`
	FuncCall         *InspectorMsgReq_Event_FuncCall   `protobuf:"bytes,2,opt,name=FuncCall" json:"FuncCall,omitempty"`
	FuncReturn       *InspectorMsgReq_Event_FuncReturn `protobuf:"bytes,3,opt,name=FuncReturn" json:"FuncReturn,omitempty"`
	Exit             *InspectorMsgReq_Event_Exit       `protobuf:"bytes,4,opt,name=Exit" json:"Exit,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *InspectorMsgReq_Event) Reset()                    { *m = InspectorMsgReq_Event{} }
func (m *InspectorMsgReq_Event) String() string            { return proto.CompactTextString(m) }
func (*InspectorMsgReq_Event) ProtoMessage()               {}
func (*InspectorMsgReq_Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InspectorMsgReq_Event) GetType() InspectorMsgReq_Event_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return InspectorMsgReq_Event_FUNC_CALL
}

func (m *InspectorMsgReq_Event) GetFuncCall() *InspectorMsgReq_Event_FuncCall {
	if m != nil {
		return m.FuncCall
	}
	return nil
}

func (m *InspectorMsgReq_Event) GetFuncReturn() *InspectorMsgReq_Event_FuncReturn {
	if m != nil {
		return m.FuncReturn
	}
	return nil
}

func (m *InspectorMsgReq_Event) GetExit() *InspectorMsgReq_Event_Exit {
	if m != nil {
		return m.Exit
	}
	return nil
}

type InspectorMsgReq_Initiation struct {
	EntityId         *string `protobuf:"bytes,1,req,name=entityId" json:"entityId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InspectorMsgReq_Initiation) Reset()                    { *m = InspectorMsgReq_Initiation{} }
func (m *InspectorMsgReq_Initiation) String() string            { return proto.CompactTextString(m) }
func (*InspectorMsgReq_Initiation) ProtoMessage()               {}
func (*InspectorMsgReq_Initiation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InspectorMsgReq_Initiation) GetEntityId() string {
	if m != nil && m.EntityId != nil {
		return *m.EntityId
	}
	return ""
}

type InspectorMsgReq_JavaSpecificFields_StackTraceElement struct {
	FileName         *string `protobuf:"bytes,1,req,name=fileName" json:"fileName,omitempty"`
	ClassName        *string `protobuf:"bytes,2,req,name=className" json:"className,omitempty"`
	MethodName       *string `protobuf:"bytes,3,req,name=methodName" json:"methodName,omitempty"`
	LineNumber       *int32  `protobuf:"varint,4,req,name=lineNumber" json:"lineNumber,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InspectorMsgReq_JavaSpecificFields_StackTraceElement) Reset() {
	*m = InspectorMsgReq_JavaSpecificFields_StackTraceElement{}
}
func (m *InspectorMsgReq_JavaSpecificFields_StackTraceElement) String() string {
	return proto.CompactTextString(m)
}
func (*InspectorMsgReq_JavaSpecificFields_StackTraceElement) ProtoMessage() {}
func (*InspectorMsgReq_JavaSpecificFields_StackTraceElement) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5}
}

func (m *InspectorMsgReq_JavaSpecificFields_StackTraceElement) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *InspectorMsgReq_JavaSpecificFields_StackTraceElement) GetClassName() string {
	if m != nil && m.ClassName != nil {
		return *m.ClassName
	}
	return ""
}

func (m *InspectorMsgReq_JavaSpecificFields_StackTraceElement) GetMethodName() string {
	if m != nil && m.MethodName != nil {
		return *m.MethodName
	}
	return ""
}

func (m *InspectorMsgReq_JavaSpecificFields_StackTraceElement) GetLineNumber() int32 {
	if m != nil && m.LineNumber != nil {
		return *m.LineNumber
	}
	return 0
}

type InspectorMsgReq_JavaSpecificFields_Params struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InspectorMsgReq_JavaSpecificFields_Params) Reset() {
	*m = InspectorMsgReq_JavaSpecificFields_Params{}
}
func (m *InspectorMsgReq_JavaSpecificFields_Params) String() string { return proto.CompactTextString(m) }
func (*InspectorMsgReq_JavaSpecificFields_Params) ProtoMessage()    {}
func (*InspectorMsgReq_JavaSpecificFields_Params) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6}
}

func (m *InspectorMsgReq_JavaSpecificFields_Params) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *InspectorMsgReq_JavaSpecificFields_Params) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type InspectorMsgReq_JavaSpecificFields struct {
	ThreadName           *string                                                 `protobuf:"bytes,1,req,name=threadName" json:"threadName,omitempty"`
	NrStackTraceElements *int32                                                  `protobuf:"varint,2,req,name=nrStackTraceElements" json:"nrStackTraceElements,omitempty"`
	StackTraceElements   []*InspectorMsgReq_JavaSpecificFields_StackTraceElement `protobuf:"bytes,3,rep,name=stackTraceElements" json:"stackTraceElements,omitempty"`
	NrParams             *int32                                                  `protobuf:"varint,4,req,name=nrParams" json:"nrParams,omitempty"`
	Params               []*InspectorMsgReq_JavaSpecificFields_Params            `protobuf:"bytes,5,rep,name=params" json:"params,omitempty"`
	XXX_unrecognized     []byte                                                  `json:"-"`
}

func (m *InspectorMsgReq_JavaSpecificFields) Reset()         { *m = InspectorMsgReq_JavaSpecificFields{} }
func (m *InspectorMsgReq_JavaSpecificFields) String() string { return proto.CompactTextString(m) }
func (*InspectorMsgReq_JavaSpecificFields) ProtoMessage()    {}
func (*InspectorMsgReq_JavaSpecificFields) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7}
}

func (m *InspectorMsgReq_JavaSpecificFields) GetThreadName() string {
	if m != nil && m.ThreadName != nil {
		return *m.ThreadName
	}
	return ""
}

func (m *InspectorMsgReq_JavaSpecificFields) GetNrStackTraceElements() int32 {
	if m != nil && m.NrStackTraceElements != nil {
		return *m.NrStackTraceElements
	}
	return 0
}

func (m *InspectorMsgReq_JavaSpecificFields) GetStackTraceElements() []*InspectorMsgReq_JavaSpecificFields_StackTraceElement {
	if m != nil {
		return m.StackTraceElements
	}
	return nil
}

func (m *InspectorMsgReq_JavaSpecificFields) GetNrParams() int32 {
	if m != nil && m.NrParams != nil {
		return *m.NrParams
	}
	return 0
}

func (m *InspectorMsgReq_JavaSpecificFields) GetParams() []*InspectorMsgReq_JavaSpecificFields_Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type InspectorMsgReq struct {
	EntityId              *string                             `protobuf:"bytes,1,req,name=entity_id" json:"entity_id,omitempty"`
	Type                  *InspectorMsgReq_Type               `protobuf:"varint,2,req,name=type,enum=pb.InspectorMsgReq_Type" json:"type,omitempty"`
	Pid                   *int32                              `protobuf:"varint,3,req,name=pid" json:"pid,omitempty"`
	Tid                   *int32                              `protobuf:"varint,4,req,name=tid" json:"tid,omitempty"`
	MsgId                 *int32                              `protobuf:"varint,5,req,name=msg_id" json:"msg_id,omitempty"`
	GaMsgId               *int32                              `protobuf:"varint,6,opt,name=ga_msg_id" json:"ga_msg_id,omitempty"`
	Event                 *InspectorMsgReq_Event              `protobuf:"bytes,7,opt,name=Event" json:"Event,omitempty"`
	Initiation            *InspectorMsgReq_Initiation         `protobuf:"bytes,8,opt,name=Initiation" json:"Initiation,omitempty"`
	HasJavaSpecificFields *int32                              `protobuf:"varint,9,req,name=HasJavaSpecificFields" json:"HasJavaSpecificFields,omitempty"`
	JavaSpecificFields    *InspectorMsgReq_JavaSpecificFields `protobuf:"bytes,10,opt,name=JavaSpecificFields" json:"JavaSpecificFields,omitempty"`
	XXX_unrecognized      []byte                              `json:"-"`
}

func (m *InspectorMsgReq) Reset()                    { *m = InspectorMsgReq{} }
func (m *InspectorMsgReq) String() string            { return proto.CompactTextString(m) }
func (*InspectorMsgReq) ProtoMessage()               {}
func (*InspectorMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *InspectorMsgReq) GetEntityId() string {
	if m != nil && m.EntityId != nil {
		return *m.EntityId
	}
	return ""
}

func (m *InspectorMsgReq) GetType() InspectorMsgReq_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return InspectorMsgReq_EVENT
}

func (m *InspectorMsgReq) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *InspectorMsgReq) GetTid() int32 {
	if m != nil && m.Tid != nil {
		return *m.Tid
	}
	return 0
}

func (m *InspectorMsgReq) GetMsgId() int32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *InspectorMsgReq) GetGaMsgId() int32 {
	if m != nil && m.GaMsgId != nil {
		return *m.GaMsgId
	}
	return 0
}

func (m *InspectorMsgReq) GetEvent() *InspectorMsgReq_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *InspectorMsgReq) GetInitiation() *InspectorMsgReq_Initiation {
	if m != nil {
		return m.Initiation
	}
	return nil
}

func (m *InspectorMsgReq) GetHasJavaSpecificFields() int32 {
	if m != nil && m.HasJavaSpecificFields != nil {
		return *m.HasJavaSpecificFields
	}
	return 0
}

func (m *InspectorMsgReq) GetJavaSpecificFields() *InspectorMsgReq_JavaSpecificFields {
	if m != nil {
		return m.JavaSpecificFields
	}
	return nil
}

type InspectorMsgRsp struct {
	Res              *InspectorMsgRsp_Result `protobuf:"varint,1,req,name=res,enum=pb.InspectorMsgRsp_Result" json:"res,omitempty"`
	MsgId            *int32                  `protobuf:"varint,2,opt,name=msg_id" json:"msg_id,omitempty"`
	GaMsgId          *int32                  `protobuf:"varint,3,opt,name=ga_msg_id" json:"ga_msg_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *InspectorMsgRsp) Reset()                    { *m = InspectorMsgRsp{} }
func (m *InspectorMsgRsp) String() string            { return proto.CompactTextString(m) }
func (*InspectorMsgRsp) ProtoMessage()               {}
func (*InspectorMsgRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *InspectorMsgRsp) GetRes() InspectorMsgRsp_Result {
	if m != nil && m.Res != nil {
		return *m.Res
	}
	return InspectorMsgRsp_ACK
}

func (m *InspectorMsgRsp) GetMsgId() int32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *InspectorMsgRsp) GetGaMsgId() int32 {
	if m != nil && m.GaMsgId != nil {
		return *m.GaMsgId
	}
	return 0
}

func init() {
	proto.RegisterType((*InspectorMsgReq_Event_FuncCall)(nil), "pb.InspectorMsgReq_Event_FuncCall")
	proto.RegisterType((*InspectorMsgReq_Event_FuncReturn)(nil), "pb.InspectorMsgReq_Event_FuncReturn")
	proto.RegisterType((*InspectorMsgReq_Event_Exit)(nil), "pb.InspectorMsgReq_Event_Exit")
	proto.RegisterType((*InspectorMsgReq_Event)(nil), "pb.InspectorMsgReq_Event")
	proto.RegisterType((*InspectorMsgReq_Initiation)(nil), "pb.InspectorMsgReq_Initiation")
	proto.RegisterType((*InspectorMsgReq_JavaSpecificFields_StackTraceElement)(nil), "pb.InspectorMsgReq_JavaSpecificFields_StackTraceElement")
	proto.RegisterType((*InspectorMsgReq_JavaSpecificFields_Params)(nil), "pb.InspectorMsgReq_JavaSpecificFields_Params")
	proto.RegisterType((*InspectorMsgReq_JavaSpecificFields)(nil), "pb.InspectorMsgReq_JavaSpecificFields")
	proto.RegisterType((*InspectorMsgReq)(nil), "pb.InspectorMsgReq")
	proto.RegisterType((*InspectorMsgRsp)(nil), "pb.InspectorMsgRsp")
	proto.RegisterEnum("pb.InspectorMsgReq_Event_Type", InspectorMsgReq_Event_Type_name, InspectorMsgReq_Event_Type_value)
	proto.RegisterEnum("pb.InspectorMsgReq_Type", InspectorMsgReq_Type_name, InspectorMsgReq_Type_value)
	proto.RegisterEnum("pb.InspectorMsgRsp_Result", InspectorMsgRsp_Result_name, InspectorMsgRsp_Result_value)
}

var fileDescriptor0 = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0x51, 0x4f, 0xd4, 0x40,
	0x10, 0xce, 0xb5, 0xd7, 0xe3, 0x6e, 0x50, 0x38, 0x36, 0x12, 0x2b, 0x51, 0x72, 0x36, 0x8a, 0x98,
	0x68, 0x63, 0x08, 0x0f, 0xbc, 0xf8, 0x00, 0x67, 0x09, 0x55, 0x2c, 0xa6, 0x14, 0xe3, 0x5b, 0xb3,
	0xf4, 0x96, 0x63, 0x63, 0xbb, 0xad, 0xdd, 0x2d, 0x11, 0x5f, 0xf5, 0x2f, 0xf8, 0x33, 0xfd, 0x09,
	0x26, 0x6e, 0xb7, 0x45, 0xe0, 0xae, 0xa7, 0xf7, 0xd4, 0xec, 0xec, 0xcc, 0xec, 0xf7, 0x7d, 0x33,
	0x5f, 0xe1, 0x3e, 0x65, 0x3c, 0x23, 0x91, 0x48, 0xf3, 0x30, 0x21, 0x9c, 0xe3, 0x31, 0xb1, 0xb3,
	0x3c, 0x15, 0x29, 0xd2, 0xb2, 0x53, 0xcb, 0x86, 0x75, 0xf7, 0xea, 0xfa, 0x3d, 0x1f, 0xfb, 0xe4,
	0x4b, 0xe8, 0x5c, 0x10, 0x26, 0xc2, 0xfd, 0x82, 0x45, 0x43, 0x1c, 0xc7, 0xe8, 0x0e, 0xb4, 0x19,
	0x4e, 0x88, 0xd9, 0x1a, 0x68, 0x9b, 0x3d, 0xeb, 0x15, 0x0c, 0x66, 0xe7, 0xfb, 0x44, 0x14, 0x39,
	0x9b, 0xa8, 0xb0, 0x61, 0xad, 0xb9, 0xc2, 0xf9, 0x4a, 0x05, 0xea, 0x43, 0x97, 0xc8, 0xef, 0x30,
	0x1d, 0x55, 0xf9, 0x86, 0xf5, 0x53, 0x83, 0xd5, 0xc6, 0x02, 0xf4, 0x02, 0xda, 0xe2, 0x32, 0xab,
	0xf2, 0x96, 0xb6, 0xd6, 0xed, 0xec, 0xd4, 0x6e, 0x4c, 0xb4, 0x03, 0x99, 0x85, 0xb6, 0xa1, 0x7b,
	0xc5, 0xc1, 0xd4, 0x06, 0xad, 0xcd, 0xc5, 0x2d, 0x6b, 0x66, 0xc5, 0x35, 0xdb, 0x1d, 0x80, 0x6b,
	0x26, 0xa6, 0xae, 0xea, 0x9e, 0xfc, 0xbb, 0xae, 0x66, 0x2d, 0xd1, 0x95, 0x8c, 0xcc, 0xb6, 0xaa,
	0x99, 0x8d, 0x4e, 0xf1, 0x96, 0x3a, 0xb6, 0x15, 0xca, 0xbb, 0xd0, 0xdb, 0x3f, 0xf1, 0x86, 0xe1,
	0x70, 0xf7, 0xf0, 0xb0, 0xdf, 0x42, 0xcb, 0xb0, 0xa8, 0x8e, 0xbe, 0x13, 0x9c, 0xf8, 0x5e, 0x5f,
	0x43, 0x5d, 0xd9, 0xf5, 0x93, 0x1b, 0xf4, 0xf5, 0x26, 0x1d, 0x5d, 0x46, 0x05, 0xc5, 0x82, 0xa6,
	0x4c, 0xe9, 0xc8, 0x04, 0x15, 0x97, 0xee, 0xa8, 0xd6, 0xfd, 0x7b, 0x0b, 0xb6, 0x27, 0x0b, 0xde,
	0xe2, 0x0b, 0x7c, 0x2c, 0x23, 0xf4, 0x8c, 0x46, 0xfb, 0x94, 0xc4, 0x23, 0x1e, 0x1e, 0x0b, 0x1c,
	0x7d, 0x0e, 0x72, 0x1c, 0x11, 0x27, 0x26, 0x49, 0x29, 0xb3, 0x6c, 0x75, 0x46, 0x63, 0xe2, 0xfd,
	0x1d, 0x21, 0x5a, 0x81, 0x5e, 0x14, 0x63, 0xce, 0x55, 0x48, 0x53, 0x21, 0x04, 0x90, 0x10, 0x71,
	0x9e, 0x8e, 0x54, 0x4c, 0xbf, 0x8a, 0xc5, 0x94, 0x11, 0xaf, 0x48, 0x4e, 0x49, 0x2e, 0x75, 0x28,
	0xa7, 0x79, 0x00, 0xcf, 0xe7, 0x00, 0xf1, 0x01, 0xe7, 0x38, 0xe1, 0xb7, 0x17, 0x47, 0x4a, 0x63,
	0x5c, 0xe0, 0xb8, 0xa8, 0x5f, 0xb4, 0x7e, 0xb7, 0xc0, 0xfa, 0x7f, 0xab, 0x12, 0x84, 0x38, 0xcf,
	0x09, 0x1e, 0xdd, 0xc0, 0xff, 0x10, 0xee, 0xb1, 0x7c, 0x8a, 0x28, 0x57, 0x8d, 0x0d, 0x14, 0x00,
	0xe2, 0xd3, 0x77, 0xfa, 0x40, 0x97, 0x63, 0xdc, 0x69, 0x1a, 0xe3, 0xbc, 0x2a, 0xb2, 0xbc, 0xe2,
	0x55, 0x49, 0x81, 0x5e, 0x43, 0x27, 0xab, 0xce, 0x86, 0xea, 0xfd, 0x72, 0xce, 0xde, 0x55, 0x13,
	0xeb, 0x97, 0x06, 0xcb, 0x13, 0xd9, 0xe5, 0x60, 0xaa, 0xa9, 0x87, 0xb4, 0x1e, 0x3b, 0xda, 0xa8,
	0x4d, 0xa2, 0x29, 0x93, 0x98, 0x0d, 0x6f, 0x54, 0xf6, 0x58, 0x04, 0x3d, 0x93, 0x45, 0xba, 0x82,
	0x26, 0x0f, 0x42, 0x1e, 0x2a, 0x9c, 0x4b, 0xd0, 0x49, 0xf8, 0xb8, 0xec, 0x68, 0xa8, 0xb3, 0x7c,
	0x64, 0x8c, 0xc3, 0x3a, 0xd4, 0x91, 0xdb, 0x6d, 0xa0, 0x4d, 0x30, 0xd4, 0x2e, 0x9b, 0x0b, 0x6a,
	0xd9, 0x1f, 0xcc, 0x5c, 0x76, 0xb4, 0x05, 0x70, 0xbd, 0xa5, 0x66, 0x77, 0xb6, 0x37, 0x6e, 0xec,
	0xf2, 0x23, 0x58, 0x3d, 0xc0, 0x7c, 0x5a, 0x09, 0xb3, 0xa7, 0xf0, 0xec, 0x01, 0x6a, 0xb8, 0x03,
	0xd5, 0x7a, 0x63, 0x3e, 0x4d, 0xad, 0xc7, 0xb5, 0xfd, 0x7a, 0x92, 0xc8, 0x47, 0xc7, 0x0b, 0xa4,
	0xf5, 0x96, 0x24, 0x52, 0xcf, 0x0d, 0xdc, 0xdd, 0xc0, 0x3d, 0x92, 0xce, 0xb3, 0x7e, 0xb4, 0x26,
	0xf4, 0xe6, 0x19, 0x7a, 0x06, 0x7a, 0x4e, 0x78, 0xfd, 0x03, 0x5a, 0x9b, 0x7a, 0x8b, 0x67, 0xb6,
	0x4f, 0x78, 0x11, 0x8b, 0x1b, 0x1a, 0x6a, 0x4a, 0xb0, 0x5b, 0x1a, 0x96, 0x7f, 0x15, 0xc3, 0x7a,
	0x0a, 0x9d, 0x3a, 0x79, 0x01, 0xf4, 0xdd, 0xe1, 0x3b, 0x09, 0xa1, 0x44, 0xe3, 0xfb, 0x47, 0xbe,
	0xf4, 0xbd, 0x8c, 0x39, 0xde, 0x9b, 0xbe, 0xbe, 0xb7, 0x02, 0xcb, 0x8c, 0x08, 0x3b, 0xe5, 0xf9,
	0xd8, 0x96, 0xe6, 0xc0, 0xdf, 0x8a, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xd4, 0xe7, 0x1d,
	0xd1, 0x05, 0x00, 0x00,
}
